# Spring 配置
spring:
  profiles:
    active: dev
  application:
    name: minio-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
# 端口
server:
  port: 19000

logging:
  level:
    com.alibaba.nacos.client.naming: error # 调整 nacos 注册中心日志级别