# Spring 配置
spring:
  profiles:
    active: dev
  application:
    name: coupon-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
  session:
    store-type: redis
# 端口
server:
  port: 9010

# Mybatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0



logging:
  level:
    com.alibaba.nacos.client.naming: error # 调整 nacos 注册中心日志级别