
# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/study_mall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.56.10
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
    # publisher-confirms: true # 过时，使用下面的配置替代
    publisher-confirm-type: correlated # 确认消息已发送到交换机(Exchange)选择确认类型为交互
    publisher-returns: true # 开启Exchange消息抵达队列确认
    template:
      mandatory: true # 只要抵达队列，以异步方式优先回调 returnCallback
    listener:
      direct:
        acknowledge-mode: manual # 手动ack
  thymeleaf:
    cache: false
  session:
    store-type: redis

logging:
  level:
    cn.study.product: debug

order:
  thread:
    core-size: 50
    max-size: 200
    keep-alive-time: 10