# Spring 配置
spring:
  profiles:
    active: dev
  application:
    name: backend-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848

# 端口
server:
  port: 8000

logging:
  level:
    com.alibaba.nacos.client.naming: error # 调整 nacos 注册中心日志级别