
spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://member-service
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://coupon-service
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://ware-service
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://admin-service
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: mall_host_route
          uri: lb://product-service
          predicates:
            - Host=mall.com,item.mall.com

        - id: search_host_route
          uri: lb://search-service
          predicates:
            - Host=search.mall.com

        - id: auth_host_route
          uri: lb://auth-service
          predicates:
            - Host=auth.mall.com

        - id: cart_host_route
          uri: lb://cart-service
          predicates:
            - Host=cart.mall.com

        - id: order_host_route
          uri: lb://order-service
          predicates:
            - Host=order.mall.com