
# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/study_mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    port: 6379
logging:
  level:
    cn.study.product: error
product:
  thread:
    core-size: 50
    max-size: 200
    keep-alive-time: 10
